#!/usr/bin/perl
#
# Push last line of the poop log to Sonic
#
# Run out of cron every five minutes
# */5 * * * * /home/dlk/bin/ppush

chomp(my $host = `hostname`);

die "I do not know what to do on $host\n" unless ($host eq 'rfovpn');

my $lcd = '/var/log/poop';
my $lfn = '/var/log/poop/poop.log';
my $rhn = 'votmoa@sh.sonic.net';
my $rfn = 'poop/poop.log';

# If log is fresher than our last push
my $fresh = 5 / 1440;  # 5 minutes in days
if (-M $lfn < $fresh) {
	# ...then copy last line of our file
	my $cmd = "tail -1 $lfn | ssh $rhn \"cat >> '$rfn'\"";
	system($cmd);
}

