#!/bin/bash

# Create the rrd database
#
# It has two gauge data sources (DS): 
#     level (treated as an integer)
#     closed (treated as binary: 0,1)
# Values are collected once per minute with a 10 minute heartbeat
# 
# Each has four archives:
#    10 days of 1m
#    90 days of 5m
#    18 months of 1h
#    10 years of 1d

rrdfile=/var/rrd/poopypi/poop.rrd

if [ -n "$1" ]; then
    rrdfile="$1"
fi

if [ -e $rrdfile ]; then
    echo "ABORT! Cowardly refusing to overwrite existing $rrdfile!"
    echo "       Manually remove it if you wish to proceed."
    exit 1
fi

set -x
rrdtool create $rrdfile \
   --no-overwrite \
   --start now-30d --step 1m \
   DS:level:GAUGE:10m:0:1024 \
   RRA:AVERAGE:0.5:1m:10d \
   RRA:AVERAGE:0.5:5m:90d \
   RRA:AVERAGE:0.5:1h:18M \
   RRA:AVERAGE:0.5:1d:10y \
   DS:closed:GAUGE:10m:0:1 \
   RRA:MAX:0.5:1m:10d \
   RRA:MAX:0.5:5m:90d \
   RRA:MAX:0.5:1h:18M \
   RRA:MAX:0.5:1d:10y \

